### ISSUE TITLE
rename to hexo-renderer-jade

### ISSUE THREAD

**Issue by ASVBPREAUBV** [hexojs/hexo-renderer-jade#20]
Is it possible to rename this repo to hexo-renderer-pug? Or at least publish it on https://www.npmjs.com/package/hexo-renderer-pug?
This may be related:
https://github.com/iwarner/hexo-renderer-pug/issues/1

**Comment by YoshinoriN** [comment]
@ASVBPREAUBV 
Thank you for your report :)
We replaced from `hexo-rendere-jade` to `hexo-rendere-pug`

> [repository](https://github.com/hexojs/hexo-renderer-pug)
> [npm](https://www.npmjs.com/package/hexo-renderer-pug)
