### ISSUE TITLE
[1]    51197 segmentation fault  hexo clean

### ISSUE THREAD

**Issue by mckobe23** [hexojs/hexo-renderer-jade#5]
hi,i have already installed jade,but i use "hexo clean" ,then throw this error

"[1]    51197 segmentation fault  hexo clean"

**Comment by zhongxia245** [comment]
I also met this problem

**Comment by yoshinorin** [comment]
We replaced this repo to [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug).
Please re-create a new issue at [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug) if you are using hexo and this problem still occurs.

Thanks :)
