### ISSUE TITLE
Jade rename to pug

### ISSUE THREAD

**Issue by mcdanielisaac** [hexojs/hexo-renderer-jade#7]
Currently getting the following warning

```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

The [Jade repo](https://github.com/jadejs/jade) says:
Jade has been renamed to Pug. You can find the new repo here: https://github.com/pugjs/jade

**Comment by ghidello** [comment]
Appearently Jade HAS to be renamed in the next few months (very few)

**Comment by Surgo** [comment]
I'll contact to npm.

**Comment by gaggle** [comment]
BTW there's also https://github.com/maxknee/hexo-render-pug, which is linked from Hexo's documentation https://hexo.io/docs/themes.html. It's even published to npm @ https://www.npmjs.com/package/hexo-render-pug with an installation description pointing to the wrong package made (`hexo-renderer-pug` vs. `hexo-render-pug`.

Le sigh, this confusion seems so unnecessary.

**Comment by demurgos** [comment]
Any news about this?

**Comment by NoahDragon** [comment]
@demurgos as the hexo-renderer-pug has been registered by others. We decide to continue use the hexo-renderer-jade, but it support pug.

**Comment by demurgos** [comment]
Thanks for the reply.
I've seen that it is registered but this package is not actively maintained. I was mainly wondering @Surgo had a reply or someone else tried to send an email. I'll try to contact the current maintainer.

**Comment by demurgos** [comment]
Hi,
As mentioned in my previous message, I sent an email to @iwarner.
He just replied and sent invitations to a few core maintainers ( @NoahDragon @JLHwung ). Could you check if you have access rights to the npm package? If so, could you reopen this issue to plan a migration path?

**Comment by JLHwung** [comment]
@demurgos Thank you for the communications.
@iwarner We don't have access to the npm package since we are not the collaborators of https://www.npmjs.com/package/hexo-renderer-pug, though we do have gained access to the GitHub repository.

@NoahDragon Any consideration on 4.x to migrate all these hexo-* package to scoped package?

**Comment by iwarner** [comment]
Give me an NPM username and I can add

**Comment by NoahDragon** [comment]
@iwarner Thank you. My NMP account is `abnerchou`, and @JLHwung is `jlhwung`. You could add any of us. We may also need your help to move the package to hexojs org. https://www.npmjs.com/org/hexojs
But we will see.

**Comment by iwarner** [comment]
Hexobot is now an owner so you can manage the others now.

➜  hexo-renderer-pug git:(master) ✗ npm owner ls
hexobot <hexojs@gmail.com>
iwarner <ian.warner@drykiss.com>

**Comment by iwarner** [comment]
Just seen the above - added abnerchou

**Comment by demurgos** [comment]
@JLHwung Using an npm scope would indeed be a great idea for hexo: it would prevent this sort of issues in the future. It would also add a way to find all the hexo packages. _npm_ recently allowed the creation of free organizations (with the limitation that the packages must be public). I'd recommend that one you create a `hexo` organization even if you don't plan to migrate right away: just to be sure that it is owned by one you.

**Comment by JLHwung** [comment]
@demurgos We have registered @hexojs but @hexo seems to be registered by someone.

**Comment by demurgos** [comment]
Ok, yes I've seen there could be a problem with `hexo`. Organization and user names share the same namespace and there is a user named `hexo`. At least it's consistent with the Github organization.

**Comment by NoahDragon** [comment]
@iwarner Thanks. Could you please do me a favor? I couldn't add the package to hexojs org, as I'm not the main contributors. I have added you to the hexojs as admin. Could you please login to the page https://www.npmjs.com/org/hexojs/team/collaborators and add the packages?

**Comment by xiaomizhou66** [comment]
所以现在遇到这个问题，是安装什么呀？
