### ISSUE TITLE
$ hexo generate -w does not work with the plugin

### ISSUE THREAD

**Issue by kouliavtsev** [hexojs/hexo-renderer-jade#8]
After installing the hexo-renderer-jade plugin, hexo generate -w stopped updating, after the templates would get edited in the editor. Is there a configuration, that I could have missed? :)

**Comment by yoshinorin** [comment]
We replaced this repo to [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug).
Please re-create a new issue at [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug) if you are using hexo and this problem still occurs.

Thanks :)
