### ISSUE TITLE
Getting post tags in index

### ISSUE THREAD

**Issue by mentos1386** [hexojs/hexo-renderer-jade#9]
Im trying to list all tags for specific post in "index" page.

im doint it this way atm.

``` jade
each post in site.posts.toArray()
    each tag in post.tags
        span!=tag
```

but tag is `null`
doing `post.tags.toArray()` also dosn't work `Converting circular structure to JSON`

**Comment by yoshinorin** [comment]
@mentos1386 
We replaced this repo to [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug).
Please re-create a new issue at [hexo-renderer-pug](https://github.com/hexojs/hexo-renderer-pug) if you are using hexo and this problem still occurs.

Thanks :)
